"use client";
/* The profile query hydrates a controlled form; this effect intentionally syncs server data once. */
/* eslint-disable react-hooks/set-state-in-effect */
import { FormEvent, useEffect, useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { Check, MapPin, UserRound } from "lucide-react";
import { api } from "@/convex/_generated/api";
import { Button } from "@/components/ui/button";
import { TextField } from "@/components/ui/field";
export default function ProfilePage(){const profile=useQuery(api.profiles.get);const save=useMutation(api.profiles.upsert);const[name,setName]=useState("");const[brandName,setBrand]=useState("");const[city,setCity]=useState("");const[country,setCountry]=useState("");const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");useEffect(()=>{if(profile){setName(profile.name);setBrand(profile.brandName);setCity(profile.city??"");setCountry(profile.country??"")}},[profile]);async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");setMessage("");try{await save({name,brandName,city:city||undefined,country:country||undefined});setMessage("Profil enregistré.")}catch(reason){setError(reason instanceof Error?reason.message:"Enregistrement impossible.")}finally{setSaving(false)}}if(profile===undefined)return <p>Chargement…</p>;return <div className="mx-auto max-w-2xl space-y-8"><header><p className="t-eyebrow text-framboise">Ton identité</p><h1 className="t-display-lg mt-3 text-prune">Profil.</h1></header><section className="rounded-[24px] bg-prune p-8 text-white"><div className="flex items-center gap-5"><span className="flex h-16 w-16 items-center justify-center rounded-full bg-framboise display-font text-3xl">{name.charAt(0).toUpperCase()||"S"}</span><div><p className="display-font text-3xl font-semibold">{name}</p><p className="text-sm font-semibold text-jaune">{brandName}</p>{(city||country)&&<p className="mt-2 flex items-center gap-1 text-xs text-white/60"><MapPin className="h-3 w-3"/>{[city,country].filter(Boolean).join(", ")}</p>}</div></div></section><form onSubmit={submit} className="space-y-6 rounded-[24px] border border-line bg-white p-6"><p className="flex items-center gap-2 font-bold text-prune"><UserRound className="h-4 w-4 text-framboise"/>Informations de l&apos;atelier</p><div className="grid gap-5 sm:grid-cols-2"><TextField label="Nom complet" required value={name} onChange={e=>setName(e.target.value)}/><TextField label="Marque" required value={brandName} onChange={e=>setBrand(e.target.value)}/><TextField label="Ville" optional value={city} onChange={e=>setCity(e.target.value)}/><TextField label="Pays" optional value={country} onChange={e=>setCountry(e.target.value)}/></div>{error&&<p className="text-error">{error}</p>}{message&&<p className="flex items-center gap-2 text-success"><Check className="h-4 w-4"/>{message}</p>}<Button disabled={saving}>{saving?"Enregistrement…":"Enregistrer"}</Button></form></div>}
