export type Status = "draft" | "published" | "closed" | "archived";
export type QuestionType = "single_choice" | "multiple_choice" | "scale" | "rating" | "yes_no" | "price" | "short_text" | "paragraph" | "ranking";

export interface User { id: string; email: string; name: string; brandName: string; city?: string | null; country?: string | null }
export interface Meta { total: number; page: number; limit: number; pages: number; hasMore: boolean }
export interface Paginated<T> { data: T[]; meta: Meta }
export interface Collection { id: string; creatorId: string; title: string; description?: string; season?: string; category?: string; targetAudience?: string; launchDate?: string; status: Status; createdAt: string; updatedAt: string; modelsCount: number; testsCount: number; responsesCount: number }
export interface FashionModel { id: string; collectionId: string; name: string; description?: string; photoUrls: string[]; sketchUrl?: string; videoUrl?: string; colors: string[]; desiredPrice?: number; sortOrder: number }
export interface Question { id: string; testId: string; text: string; type: QuestionType; required: boolean; options: string[]; min?: number; max?: number; sortOrder: number; helpText?: string; modelId?: string }
export interface TestSettings { randomizeQuestions: boolean; requireAllQuestions: boolean; completionMessage: string; closesAt?: string; maxResponses?: number; anonymousResponses: boolean; collectRespondentProfile: string[] }
export interface FashionTest { id: string; collectionId: string; slug: string; title: string; description?: string; status: Status; settings: TestSettings; createdAt: string; updatedAt: string; modelsCount: number; questions: Question[]; responsesCount: number; publicUrl: string | null }
export interface CollectionDetail { collection: Collection; models: FashionModel[]; tests: FashionTest[] }
export interface PublicTest { slug: string; title: string; description?: string; settings: TestSettings; collection: { title: string; description?: string; season?: string; category?: string; targetAudience?: string }; models: Array<Omit<FashionModel, "collectionId">>; questions: Question[] }
export interface Analytics { testId: string; executiveSummary: string; desirabilityScore: number; unsoldRiskScore: number; unsoldRiskLabel: string; visitors: number | null; responses: number; conversionRate: number | null; averageResponseSeconds: number; shares: number; sharesByChannel: Record<string, number>; abandonmentRate: number | null; trafficMeasurementStatus: string; demographics: { cities: Record<string, number>; countries: Record<string, number>; sex: Record<string, number>; averageAge: number }; modelBreakdown: Array<{ modelId: string; questionsCount: number; responsesWithAnswer: number; answerRate: number; answerDistribution: Record<string, number> }>; funnel: Array<{ questionId: string; text: string; answerCount: number; answerRate: number }>; priceDistribution: Array<{ label: string; count: number }>; questionBreakdown: Array<{ questionId: string; text: string; type: QuestionType; required: boolean; answersCount: number; distribution: Record<string, number>; average: number | null }> }
export interface Recommendation { priority: "high" | "medium" | "low"; category: "production" | "pricing" | "audience" | "content" | "risk"; message: string; rationale?: string }
export interface Recommendations { provider: "local" | "imole"; dataPolicy: string; recommendations: Recommendation[]; generatedAt: string }
