"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { FormEvent, Suspense, useState } from "react";
import { Button } from "@/components/ui/button";
import { TextField } from "@/components/ui/field";
import { apiFetch } from "@/lib/api";
function Form(){const token=useSearchParams().get("token")??"";const[done,setDone]=useState(false);const[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const password=String(f.get("password"));if(password!==String(f.get("confirm"))){setError("Les mots de passe ne correspondent pas.");return}try{await apiFetch("auth/reset-password",{method:"POST",body:JSON.stringify({token,newPassword:password})});setDone(true)}catch(reason){setError(reason instanceof Error?reason.message:"Lien invalide ou expiré.")}}return <main className="grid min-h-screen place-items-center bg-canvas p-5"><form onSubmit={submit} className="w-full max-w-md space-y-6 rounded-[24px] border border-line bg-white p-8"><p className="t-eyebrow text-framboise">Sécurité</p><h1 className="display-font text-4xl font-semibold text-prune">Nouveau mot de passe.</h1>{!token?<p className="text-error">Le lien de réinitialisation est incomplet.</p>:done?<><p className="rounded-[14px] bg-success-clair p-4 text-success">Ton mot de passe a été modifié.</p><Link href="/login" className="block text-center font-bold text-framboise">Se connecter</Link></>:<><TextField label="Nouveau mot de passe" name="password" type="password" minLength={8} required/><TextField label="Confirmer" name="confirm" type="password" minLength={8} required/>{error&&<p className="text-error">{error}</p>}<Button className="w-full">Enregistrer</Button></>}</form></main>}
export default function ResetPassword(){return <Suspense><Form/></Suspense>}
